apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  labels:
    app: notifications-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
      - name: notifications-service
        image: taskflow/notifications-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: notifications-secrets
              key: rabbitmq-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: notifications-secrets
              key: redis-url
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
